### ISSUE TITLE
Compile for arm64e?

### ISSUE THREAD

**Issue by mml** [leonelhs/giac_sources#1]
Hi.  I've tried using the existing x86_64 package on an M1 Mac, but I'm guessing it uses AVX extensions or something similar...

I wonder if it's possible to do a build generating a fat binaries?

```
tillandsia:/Applications/Xcas.app/Contents/MacOS% uname -m
arm64
tillandsia:/Applications/Xcas.app/Contents/MacOS% sw_vers
ProductName:	macOS
ProductVersion:	11.6.1
BuildVersion:	20G224
tillandsia:/Applications/Xcas.app/Contents/MacOS% ./icas '2+2'
// Using locale /Applications/Xcas.app/Contents/usr/share/locale/
// en_US.UTF-8
// Maximum number of parallel threads 1
Added 0 synonyms
4
// dclock2 0.000397
// Time 0
// Total time 0
tillandsia:/Applications/Xcas.app/Contents/MacOS% ./icas '30!'
// Using locale /Applications/Xcas.app/Contents/usr/share/locale/
// en_US.UTF-8
// Maximum number of parallel threads 1
Added 0 synonyms
zsh: illegal hardware instruction  ./icas '30!'
```

**Comment by leonelhs** [comment]
I think it would be better for you build it on your M1 machine, giac lib its already running over arm64 as you can see in others apps like geogebra. 
```
./configure \
--with-included-gettext=yes \
--enable-micropy=no \
--enable-quickjs=no
```

**Comment by acasetta2A** [comment]
Hello, I need too xcas for a mac M1 .  Can you please detail how to build it myself , i 'm afraid to do too many error. Thank you for your work

**Comment by acasetta2A** [comment]
I tried and if ./configure seems to be ok, 
after make, 
i have an error : 
In file included from input_lexer.ll:53:
In file included from ./giacPCH.h:4:
./first.h:386:10: fatal error: 'gmp.h' file not found
#include "gmp.h"
  
what is this gmp.h file or how to go further .
Thank you.
